//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumaranalloorTempleAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kdtadmin3K365DBEntities : DbContext
    {
        public kdtadmin3K365DBEntities()
            : base("name=kdtadmin3K365DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diety> Dieties { get; set; }
        public virtual DbSet<Vazhipadu> Vazhipadus { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    }
}
